enum Ingredient: String, CaseIterable {
    case spinach = "Spinach"
    case broccoli = "Broccoli"
    case carrot = "Carrot"
    case pasta = "Pasta"
    case sauce = "Tomato sauce"
    case water = "Water"
    case coffee = "Coffee"
    case cream = "Cream"
    case flour = "Flour"
    case sugar = "Sugar"
    case butter = "Butter"
    case eggs = "Eggs"
    case tomatoes = "Tomatoes"
    case cucumber = "Cucumber"
    case redOnion = "Red Onion"
    case fetaCheese = "Feta Cheese"
    case olives = "Olives"
    case chicken = "Chicken"
    case bread = "Bread"
    case cheese = "Cheese"
    case lettuce = "Lettuce"
    case beef = "Beef"
    case lemon = "Lemon"
    case orange = "Orange"
    case chocolate = "Chocolate"
    case vanilla = "Vanilla"
    case berries = "Berries"
    case sparklingWater = "Sparkling Water"
    case espresso = "Espresso"
    case milk = "Milk"
    case ice = "Ice"
    case mint = "Mint"
}

